### ISSUE TITLE
 Consol windows are not restored under Windows 10

### ISSUE THREAD

**Issue by MaxMayya** [nguyenngoclongdev/vs-terminal-keeper#1]
**Describe the bug**
`tput` is not recognized and so consols are not restored

**To Reproduce**
start VScode

**Expected behavior**

> PS C:\  tput reset
> tput : The term 'tput' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the 
> path is correct and try again.
> At line:1 char:2
> +  tput reset
> +  \~~~~
>     + CategoryInfo          : ObjectNotFound: (tput:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException

**Platform:** 
 - OS: Windows10 Pro
 - vscode version: 1.80.1
 - extension version: V1.1.8

**Comment by nguyenngoclongdev** [comment]
@MaxMayya Thank you for reporting. I will try to reproduce and fix the issue as soon as possible.

**Comment by nguyenngoclongdev** [comment]
Hi @MaxMayya, I have fixed the bug in version 1.1.9.

Basically, for Windows system, I will use the `cls` command to clear the terminal before sending the commands that you defined in the settings file. For MacOS and Linux, I will still use the `tput reset` command.

Since I have only worked on MacOS and Ubuntu, I am not sure whether the fix will work on your systems. If it works well, please provide me with your feedback.

Additionally, I have added an option called `noClear` in the settings, which allows you to turn off the clear function if you feel it is unnecessary.
