### ISSUE TITLE
VS Code global configuration, instead of configuration file per project

### ISSUE THREAD

**Issue by pauloendoh** [nguyenngoclongdev/vs-terminal-keeper#14]
**Please describe feature/problem details and solution you'd like.**
I don't want to have a sessions.json file in each of my projects just to set up my terminals, specially for work related projects. Would it be possible to attach these configurations to the user settings (JSON) instead?

**Describe alternatives you've considered**
Terminal keeper adds commands to the command palette, but does not add any configurable settings in the user settings JSON.

**Comment by johurul-haque** [comment]
I would love to see this. I want to add some suggestions:

- If there's no `sessions.json` file, activating the terminal session would use the globally defined configurations.
- If there is a `sessions.json` it'll use that instead of the global configurations.
- And for the case where both of them are not defined activating the terminal session will create a `sessions.json` file (which is the current behavior).
