### ISSUE TITLE
Icons doesnt func in MAC

### ISSUE THREAD

**Issue by Bryan-Herrera-DEV** [nguyenngoclongdev/vs-terminal-keeper#2]
**Describe the bug**
Icons not activate in mac but in windows no problem

**To Reproduce**
<img width="1439" alt="image" src="https://github.com/nguyenngoclongdev/vs-terminal-keeper/assets/50712646/4c9c5614-0e47-4106-b0a6-0521cf341a4a">
<img width="1439" alt="image" src="https://github.com/nguyenngoclongdev/vs-terminal-keeper/assets/50712646/6eff1c15-c389-47ee-9aa2-b831ae9026f9">

**Expected behavior**

**Platform:** 
 - OS: Mac

**Comment by nguyenngoclongdev** [comment]
@Bryan-Herrera-DEV Thank for reporting.

I also use macOS, and this extension was developed on it. The icon on my machine displays normally.

However, I will investigate this issue.
It would be helpful if you could provide me with more information, such as your macOS version and the terminal you are using (bash or zsh).

**Comment by nguyenngoclongdev** [comment]
After investigating, it seems that this issue is caused by a VS Code API. I have noticed that there are quite a few reports on issues with using the VS Code API, not only regarding incorrect icon behavior but also similar issues with colors.

https://github.com/microsoft/vscode/issues/171082
https://github.com/microsoft/vscode/issues/167643
https://github.com/VSCodeTriageBot/testissues/issues/15028

There is a temporary solution to fix this issue, which is to configure the `shellPath` on each terminal setting. Some users have configured the `shellPath` on each terminal setting, and have reported that the icon and color display correctly. I am not sure if it works, but you can try it out.

For example:

```json
{
    "$schema": "https://cdn.statically.io/gh/nguyenngoclongdev/cdn/main/schema/v7/terminal-keeper.json",
    "theme": "tribe",
    "active": "default",
    "activateOnStartup": false,
    "keepExistingTerminals": false,
    "sessions": {
        "default": [
            [
                {
                    "name": "ssh:ubuntu",
                    "shellPath": "/usr/local/bin/zsh", 👈
                    "commands": [
                        "echo hello1"
                    ]
                },
                {
                    "name": "ssh:mint",
                    "shellPath": "/usr/local/bin/zsh", 👈
                    "commands": [
                        "echo hello2"
                    ]
                },
                {
                    "name": "ssh:macos",
                    "shellPath": "/usr/local/bin/zsh", 👈
                    "commands": [
                        "echo hello3"
                    ]
                },
                {
                    "name": "ssh:windows",
                    "shellPath": "/usr/local/bin/zsh", 👈
                    "commands": [
                        "echo hello4"
                    ]
                }
            ]
        ]
    }
}
```

Use `which zsh` to get the path of the zsh shell on your machine.
